[package]
name = "minos"
version = "0.1.0"
authors = ["Jordi Polo Carres <mumismo@gmail.com>"]
description = """
Minos is a command line tool to generate and run scenarios against
APIs described by OpenAPI files.
"""
homepage = "https://github.com/JordiPolo/minos"
repository = "https://github.com/JordiPolo/minos"
readme = "README.md"
keywords = ["openapi", "testing", "cli"]
categories = ["command-line-utilities", "api"]
license = "Unlicense OR MIT"
autotests = false

edition = "2018"

[dependencies]
regex = "1.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "*"
reqwest = { version = "0.10", default-features = false, features = ["json", "rustls-tls"] }
structopt = "0.3"
termcolor = "1.0"
uuid = { version = ">= 0.6", features = ["v4"] }
rand = "0.7.0"
chrono = "0.4"
openapiv3 = "0.3.2"
#openapi_utils = { path = "../../oasproxy/openapi_utils" }
openapi_utils = "0.2"
thiserror = "1.0"
valico = "3"
log = "0.4"
env_logger = "0.7"
http = "*"
shellexpand = "2.0"
itertools = "0.9"
comfy-table = "0.1.0"
lazy_static = "*"
tokio = { version = "0.2", features = ["full"] }
#mauth-client = { path = "../mauth-client-rust"}
hyper = "*"


[profile.dev]
debug = 0

[profile.release]
opt-level = 3
lto = true
panic = 'abort'
