[package]
name = "minos"
version = "0.1.0"
authors = ["Jordi Polo Carres <mumismo@gmail.com>"]
description = """
Minos is a command line tool to generate and run scenarios against
APIs described by OpenAPI files.
"""
homepage = "https://github.com/JordiPolo/minos"
repository = "https://github.com/JordiPolo/minos"
readme = "README.md"
keywords = ["openapi", "testing", "cli"]
categories = ["command-line-utilities", "api"]
license = "Unlicense OR MIT"
autotests = false

edition = "2018"

[dependencies]
regex = "1.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "*"
reqwest = { version = "0.10", features = ["blocking"] }
structopt = "0.3"
termcolor = "1.0"
uuid = { version = ">= 0.6", features = ["v4"] }
rand = "0.7.0"
chrono = "0.4"
openapiv3 = "0.3.0"
#openapi_utils = { path = "../../oasproxy/openapi_utils" }
openapi_utils = "0.2"
thiserror = "1.0"
valico = "3"
log = "0.4"
env_logger = "0.7"
http = "*"
shellexpand = "1.0"
itertools = "0.8"
comfy-table = "0.0.6"

[patch.crates-io]
openapiv3 = { git = "https://github.com/glademiller/openapiv3", branch = "master" }


[profile.dev]
debug=0

[profile.release]
opt-level = 3
lto = true
panic = 'abort'
